apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  tenantid: ZjI0MmIwMDktNDZmMy00YTUxLTljMDItYTllYjY3MzUxMTky
  subscriptionid: OTU3Yzg5NzQtOTA4NS00MjA0LTk3MjEtMmM3ODNjMTYzMjQ0
  clientid: ZmIxNGFlODItMDRkMi00M2Y0LWJkZTUtNGM0NDAyYjk2MjVl
  clientsecret: aW1HSi5wdjNMenctOmRJSHhXZFt5cVJRYkZhdUI0NDE=